apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "warm-metal-csi-driver.fullname" . }}-controller
  labels:
    {{- include "warm-metal-csi-driver.controllerplugin.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "warm-metal-csi-driver.controllerplugin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "warm-metal-csi-driver.controllerplugin.labels" . | nindent 8 }}
    spec:
      containers:
        - name: csi-provisioner
          image: "{{ .Values.csiExternalProvisioner.image.repository }}:{{ .Values.csiExternalProvisioner.image.tag }}"
          imagePullPolicy: {{ .Values.csiLivenessProbe.image.pullPolicy }}
          args:
            - "--csi-address=/csi/csi.sock"
          {{- with .Values.csiExternalProvisioner.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: liveness-probe
          image: "{{ .Values.csiLivenessProbe.image.repository }}:{{ .Values.csiLivenessProbe.image.tag }}"
          imagePullPolicy: {{ .Values.csiLivenessProbe.image.pullPolicy }}
          args:
            - "--csi-address=/csi/csi.sock"
            - "--http-endpoint=:9809"
            - "-v={{ .Values.logLevel }}"
          {{- with .Values.csiLivenessProbe.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: csi-plugin
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --node=$(KUBE_NODE_NAME)
            - --node-plugin-sa={{ include "warm-metal-csi-driver.fullname" . }}-nodeplugin
            - "-v={{ .Values.logLevel }}"
            - "--mode=controller"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: CRI_ADDR
              value: {{ .Values.runtime.engine }}://{{ .Values.runtime.socketPath }}
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          {{- with .Values.csiPlugin.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.csiPlugin.image.repository }}:{{ .Values.csiPlugin.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.csiPlugin.image.pullPolicy }}
          ports:
            - containerPort: 9809
              name: metrics
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.csiPlugin.livenessProbe | nindent 12}}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      serviceAccountName: {{ include "warm-metal-csi-driver.fullname" . }}-controller
      volumes:
        - emptyDir:
            medium: "Memory"
          name: socket-dir
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}