apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "warm-metal-csi-driver.fullname" . }}-credential-provider-config
  labels:
    {{- include "warm-metal-csi-driver.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "apiVersion": "kubelet.config.k8s.io/v1",
      "kind": "CredentialProviderConfig",
      "providers": [
        {
          "name": "ecr-credential-provider",
          "matchImages": [
            - "*.dkr.ecr.*.amazonaws.com"
            - "*.dkr.ecr.*.amazonaws.com.cn"
            - "*.dkr.ecr-fips.*.amazonaws.com"
          ],
          "defaultCacheDuration": "12h",
          "apiVersion": "credentialprovider.kubelet.k8s.io/v1"
        },
        {
          "name": "gcp-credential-provider",
          "matchImages": [
            "gcr.io",
            "*.gcr.io",
            "container.cloud.google.com",
            "*.pkg.dev"
          ],
          "defaultCacheDuration": "12h",
          "apiVersion": "credentialprovider.kubelet.k8s.io/v1"
        },
        {
          "name": "acr-credential-provider",
          "matchImages": [
            "*.azurecr.io",
            "*.azurecr.cn",
            "*.azurecr.us",
            "*.azurecr.de",
            "*.azurecr.custom"
          ],
          "defaultCacheDuration": "12h",
          "apiVersion": "credentialprovider.kubelet.k8s.io/v1"
        }
      ]
    }
