apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: csi-image-warm-metal
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-image-warm-metal
  template:
    metadata:
      labels:
        app: csi-image-warm-metal
    spec:
      containers:
        - args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path={{ .Values.kubletRoot }}/plugins/csi-image.warm-metal.tech/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: {{ .Values.csiNodeDriverRegistrar.image.repository }}:{{ .Values.csiNodeDriverRegistrar.image.tag }}
          imagePullPolicy: IfNotPresent
          name: node-driver-registrar
          resources: {}
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /registration
              name: registration-dir
        - args:
            - --endpoint=$(CSI_ENDPOINT)
            - --node=$(KUBE_NODE_NAME)
            - --runtime-addr=$(CRI_ADDR)
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: CRI_ADDR
              value: {{ .Values.runtime.engine }}://{{ .Values.runtime.socketPath }}
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          name: plugin
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: {{ .Values.kubletRoot }}/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - mountPath: {{ .Values.runtime.socketPath }}
              name: runtime-socket
            - mountPath: {{ .Values.snapshotRoot }}
              mountPropagation: Bidirectional
              name: snapshot-root-0
      hostNetwork: true
      serviceAccountName: csi-image-warm-metal
      volumes:
        - hostPath:
            path: {{ .Values.kubletRoot }}/plugins/csi-image.warm-metal.tech
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: {{ .Values.kubletRoot }}/pods
            type: DirectoryOrCreate
          name: mountpoint-dir
        - hostPath:
            path: {{ .Values.kubletRoot }}/plugins_registry
            type: Directory
          name: registration-dir
        - hostPath:
            path: {{ .Values.runtime.socketPath }}
            type: Socket
          name: runtime-socket
        - hostPath:
            path: {{ .Values.snapshotRoot }}
            type: Directory
          name: snapshot-root-0
  updateStrategy: {}