{{- if or (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1alpha1") }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "warm-metal-csi-driver.fullname" . }}
spec:
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
      scheme: http
      {{- if .Values.podMonitor.interval }}
      interval: {{ .Values.podMonitor.interval }}
      {{- end }}
      {{- if .Values.podMonitor.timeout }}
      scrapeTimeout: {{ .Values.podMonitor.timeout }}
        {{- end }}
    - path: /metrics
      port: metrics2
      scheme: http
      {{- if .Values.podMonitor.interval }}
      interval: {{ .Values.podMonitor.interval }}
      {{- end }}
      {{- if .Values.podMonitor.timeout }}
      scrapeTimeout: {{ .Values.podMonitor.timeout }}
        {{- end }}
  jobLabel: {{ include "warm-metal-csi-driver.fullname" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
    {{- include "warm-metal-csi-driver.selectorLabels" . | nindent 6 }}
{{end}}
