runtime:
  engine: cri-o
  socketPath: /var/run/crio/crio.sock
kubeletRoot: /var/lib/kubelet
snapshotRoot: /var/lib/containers/storage
crioRuntimeRoot: /run/containers/storage
crioMountProgram: /usr/local/bin/fuse-overlayfs
logLevel: 4
enableDaemonImageCredentialCache:
pullImageSecretForDaemonset:

csiPlugin:
  resources: {}
  image:
    tag: ""
    repository: docker.io/warmmetal/csi-image
    pullPolicy: IfNotPresent
  livenessProbe:
    httpGet:
      path: /healthz
      port: metrics
    failureThreshold: 5
    initialDelaySeconds: 10
    timeoutSeconds: 10
    periodSeconds: 60
csiLivenessProbe:
  resources: {}
  image:
    repository: registry.k8s.io/sig-storage/livenessprobe
    tag: v2.10.0
    pullPolicy: IfNotPresent
csiNodeDriverRegistrar:
  resources: {}
  image:
    repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
    tag: v2.8.0
    pullPolicy: IfNotPresent
csiExternalProvisioner:
  resources: {}
  image:
    repository: registry.k8s.io/sig-storage/csi-provisioner
    tag: v3.5.0
    pullPolicy: IfNotPresent
tolerations: {}
affinity: {}
nodeSelector: {}

fullnameOverride: ""

podMonitor:
  enabled: true
  interval: 30s
  timeout: 10s
