---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi-image.warm-metal.tech
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-image-warm-metal
  namespace: kube-system
---

---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: csi-image-warm-metal
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resourceNames:
      - csi-image-warm-metal
    resources:
      - serviceaccounts
    verbs:
      - get
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-image-warm-metal
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: csi-image-warm-metal
subjects:
  - kind: ServiceAccount
    name: csi-image-warm-metal
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: csi-image-warm-metal
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-image-warm-metal
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: csi-image-warm-metal
    spec:
      containers:
        - args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-image.warm-metal.tech/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - rm -rf /registration/csi-image.warm-metal.tech /registration/csi-image.warm-metal.tech-reg.sock
          name: node-driver-registrar
          resources: {}
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /registration
              name: registration-dir
        - args:
            - --endpoint=$(CSI_ENDPOINT)
            - --node=$(KUBE_NODE_NAME)
            - --runtime-addr=$(CRI_ADDR)
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: CRI_ADDR
              value: cri-o:///var/run/crio/crio.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: docker.io/warmmetal/csi-image:v0.5.1
          imagePullPolicy: IfNotPresent
          name: plugin
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - mountPath: /var/run/crio/crio.sock
              name: runtime-socket
            - mountPath: /var/lib/containers/storage
              mountPropagation: Bidirectional
              name: crio-root
            - mountPath: /run/containers/storage
              mountPropagation: Bidirectional
              name: crio-run-root
      hostNetwork: false
      serviceAccountName: csi-image-warm-metal
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-image.warm-metal.tech
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
          name: mountpoint-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          name: registration-dir
        - hostPath:
            path: /var/run/crio/crio.sock
            type: Socket
          name: runtime-socket
        - hostPath:
            path: /var/lib/containers/storage
            type: Directory
          name: crio-root
        - hostPath:
            path: /run/containers/storage
            type: Directory
          name: crio-run-root
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0