name: backward-compatibility-5mins
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start a kind cluster with containerd
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind-${{ github.run_id }}
          kubectl_version: "v1.25.2"
          config: ./hack/ci/containerd-cluster-conf.yaml
      - name: Build image
        run: ./hack/ci/build.sh
      - name: Test compatibility with versions prior to v0.4.2
        run: ./test/integration/backward-compatability.sh
