name: docker-containerd
on:
  workflow_dispatch:
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opsgang/ga-setup-minikube@v0.1.2
        with:
          minikube-version: 'v1.35.0'
          k8s-version: '1.32.2'
      - name: Start a Kubernetes cluster with docker
        run: ./hack/ci/setup_docker_cluster.sh
      - name: Build image
        run: ./hack/ci/build.sh
      - name: Install the CSI Driver
        run: ./hack/ci/install_driver_containerd.sh
      - name: Run integration Tests
        run: ./hack/ci/test.sh
      - name: Uninstall the CSI Driver
        run: ./hack/ci/uninstall_driver_containerd.sh
